artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_url: "https://github.com/HarishKumarSedu/End_to_End_Ml/raw/main/artifacts/data_ingestion/data.zip"
  data_local_file: artifacts/data_ingestion/data.zip
  data_unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  data_local_file: artifacts/data_ingestion/winequality-red.csv
  data_validation_status_file: artifacts/data_validation/VALIDATION_STATUS.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_local_file: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir:         artifacts/model_trainer
  train_data_path:  artifacts/data_transformation/train.csv
  test_data_path:   artifacts/data_transformation/test.csv
  model_name:       model.joblib

model_evaluation:
  root_dir:           artifacts/model_evaluation
  test_data_path:     artifacts/data_transformation/test.csv
  model_path:         artifacts/model_trainer/model.joblib
  metric_file_name:   artifacts/model_evaluation/metrics.json