COLUMNS: 
  fixed acidity:  fixed acidity
  volatile acidity:  volatile acidity
  citric acid: citric acid
  residual sugar: residual sugar
  chlorides: chlorides
  free sulfur dioxide: free sulfur dioxide
  total sulfur dioxide: total sulfur dioxide
  density: density
  pH: pH
  sulphates: sulphates
  alcohol: alcohol

TARGET : quality